config/routes.rb
Rails.application.routes.draw do

  # resources :profiles
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Spree::Core::Engine.routes.draw do

    resources :charges
    resources :profiles
  	get "about-us" => "home#about_us"
  	get 'contact-us' => 'home#contact_us'
  	get 'shop' => 'home#shop'
  	get 'how-it-works' => 'home#how_we_works'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
	acts_as_nested_set
	belongs_to :spree_user
	after_create :generate_uuid
	
	belongs_to :parent, class_name: "Profile", foreign_key: :parent_id
	has_many :children, class_name: "Profile", foreign_key: :parent_id


	def generate_uuid
		self.uuid = SecureRandom.uuid
		self.save
	end


	def full_name
		first_name + last_name	
	end


end

app/models/spree/user_decorator.rb
module Spree
	User.class_eval do
		has_many :profiles
		



	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def user_must_be_active!
  	if current_spree_user
	    if !current_spree_user.active?
        if current_spree_user.profiles.first
          if current_spree_user.profiles.first.active
          else
            flash[:error] = "User Account is not active"
            redirect_to profile_path(current_spree_user.profiles.first.id)
          end
        else
          flash[:error] = "User Account is not active"
	        redirect_to new_profile_path
        end
	     end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :check_validate_referral, only: :create
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    # @profile = Profile.new(profile_params.merge(user_id:current_spree_user.id))
    respond_to do |format|
      p @profile
      # if @profile.save
      #   format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
      #   format.json { render :show, status: :created, location: @profile }
      # else
      #   format.html { render :new }
      #   format.json { render json: @profile.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :uuid)
    end

    def check_validate_referral
      @p_profile = Profile.find_by_uuid(params[:uuid])
      if @p_profile.children.count < 1
        @profile = @p_profile.children.new(profile_params.merge(user_id:current_spree_user.id))
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
        # return false
      end
    end
end

app/controllers/spree/charges_controller.rb
module Spree
	class ChargesController < Spree::BaseController
    def new
    end

    def create
      # Amount in cents
      @amount = 150

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
      if charge.save 
        current_spree_user.profiles.first.update(active: true)
        redirect_to profiles_path
      end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
  end
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do
	before_filter :user_must_be_active!
	
	def index
	end

	def shop
	end

	def about_us
	end

	def contact_us	
	end

	def how_we_works
	end

end

app/controllers/spree/profiles_controller.rb
module Spree
	class ProfilesController < Spree::BaseController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :validate_profile, only: [:new]
  before_action :check_validate_referral, only: :create

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = current_spree_user.profiles.limit(5)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    if @profile.active == false
      redirect_to new_charge_path
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    # @profile = Profile.new(profile_params.merge(user_id:current_spree_user.id))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_validate_referral
      @p_profile = Profile.find_by_uuid(params[:profile][:referral_id])
      p @p_profile



      if @p_profile.children.count < 1
        @profile = @p_profile.children.new(profile_params.merge(user_id:current_spree_user.id))
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
        # return false
      end
    end

    def validate_profile
      if current_spree_user.profiles.count >= 5
        redirect_to '/'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :referral_id)
    end
end
end

app/controllers/spree/user_registartions_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do


	def new
		if !current_spree_user
    	@user = Spree::User.new
    else
    	redirect_to root_path, notice: "Already signed in"
    end
  end

  private

  def spree_user_params
    params.require(:spree_user).permit(Spree::PermittedAttributes.user_attributes, :referral_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spree/charges/new.html.erb
<div class="container">
  <div class="payment-rule">
    <div class="row">
      <div class="col-md-8">
        <div class="discription">
          <h2 class="heading">What are the online payment rules?</h1>
          <div class="">When you are required to enter your billing information and credit card details during the payment process, you will see the link to the right of the screen called ‘See online payment rules’.</div>
          <div class="col-md-8">
            <li class="rules"><i class="fa fa-check" aria-hidden="true"></i></li>
            <li class="rules"><i class="fa fa-check" aria-hidden="true"></i></li>
          </div>
        </div>
      </div>
      <div class="col-md-4 payment-form">
        <div class="amount">
          <div class=""> Subscription Amount</div>
          <div class="price">150</div>
        </div>
        <div class="payment-form-btn">
          <%= form_tag charges_path do %>
            <article>
              <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
              <% end %>
              <label class="amount">
                <span>Amount: $5.00</span>
              </label>
            </article>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="A month's subscription"
                    data-amount="500"
                    data-locale="auto">
                  
            </script>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>
  <div>
    
  </div>
</div>

app/views/spree/home/contact_us.html.slim
.container
	h1 contact us

app/views/spree/home/how_we_works.html.slim
.container
	.how-its-works
		h1 How It Works?
		hr
		.joining-details
			h4 Joining Fee Rs.300/- 
			ul
				li -> You will Get Rs.100/- Per Person for PRIME Package Sale Every Level up to 20 Level.
				li -> One Person need to Join at least 3 Direct Members. If you join more than 3 Directs People then Automatically it will spill in next levels.
				li -> 1st level to 20th level incentive Rs.100/- Will Continue to be Received (T&C Apply).
				li -> Monthly Renewal Charges Apply For Every Upgrade Package.
				li -> Renewal charges will be Automatically deducted from there payment, which will continue to be received in next month.
				li -> Minimum Payment Withdrawal Rs.300/-
		.term-n-condition
			ul
				li Lorem ipsum dolor sit amet, consectetur adipisicing elit.

app/views/spree/home/index.html.slim
section#slider
  .container
    .row
      .col-sm-12
        #slider-carousel.carousel.slide data-ride="carousel" 
          ol.carousel-indicators
            li.active data-slide-to="0" data-target="#slider-carousel" 
            li data-slide-to="1" data-target="#slider-carousel" 
            li data-slide-to="2" data-target="#slider-carousel" 
          .carousel-inner
            .item.active
              .col-sm-6
                h1
                  span> 1 
                  |-MAN
                h2 CAN MAKE DIFFERENCE
                p  We believe that if you can work, then you should earn. We provide you the opportunity of work in Part-Time jobs from your home. No need to go anywhere, just earn money with working from your Home and be a self employer!
                button.btn.btn-default.get type="button"  Get it now
              .col-sm-6
                = image_tag "tree.jpg", alt: '', class:"girl img-responsive"
                / img.girl.img-responsive alt="" src="images/home/girl1.jpg"
                / img.pricing alt="" src="images/home/pricing.png"
            .item
              .col-sm-6
                h1
                  span> Our Mission Our Vision
                h2 Be successful with us
                p The program you are being presented with here holds the potential to change your life, for the better, forever.We sincerely hope you make the most of the Income info Opportunity and we welcome your valuable, long-term participation!
                button.btn.btn-default.get type="button"  Get it now
              .col-sm-6
                = image_tag "money.jpg", alt: '', class:"girl img-responsive"
                / img.girl.img-responsive alt="" src="images/home/girl2.jpg"
                / img.pricing alt="" src="images/home/pricing.png"
            .item
              .col-sm-6
                h1
                  span> E
                  |-SHOPPER
                h2 Free Ecommerce Template
                p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                button.btn.btn-default.get type="button"  Get it now
              .col-sm-6
                = image_tag "girl3.jpg", alt: '', class:"girl img-responsive"
                = image_tag "pricing.png", alt: '', class:"pricing"
                / img.girl.img-responsive alt="" src="images/home/girl3.jpg"
                / img.pricing alt="" src="images/home/pricing.png"
          a.left.control-carousel.hidden-xs data-slide="prev" href="#slider-carousel" 
            i.fa.fa-angle-left
          a.right.control-carousel.hidden-xs data-slide="next" href="#slider-carousel" 
            i.fa.fa-angle-right
section#body-content
  .row
    .col-sm-12
      .heading-section
        h1 If You Help Enough Other People Get What They Want in LIFE, You can Have Everything You Want in LIFE!
    .col-sm-12
      .text-section
        p A unique business venture promoted by a group of dedicated and successful professionals engaged in Traditional Business, Legal Advisory, Corporate Consultancy, IT Consultancy, Network marketing administration, Business and Personality Development Trainers. Company’s main focus is to offer every Indian citizen who have aspiration and willingness to invest genuine efforts to achieve what they aspire and deserve, through a genuine and fantastic opportunity in a multilevel marketing business.
        ul
          li We firmly believes in forming meaningful, mutually rewarding and long lasting family & business associations, which are built on honesty, trust and thorough professionalism with proper trainings and motivation by top most personalities in the field.
          li Mission and Purpose is to reach out and help people to increase their economic status.
          li Providing world class support, as well as the best and reliable system.
          li System honest and sincere security.
          li Best control panel to monitor the earning.
          li Payment are made instantly.
          li Honesty and quality service.
          li To provide 100% risk Free “Golden business opportunity” to each and every hand.
section#happier-life
  .row
    .col-sm-12
      .happier-wrap
        button.btn.btn-default type="button"  Get it now

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
    <link href="https://fonts.googleapis.com/css?family=Alegreya|Kreon" rel="stylesheet">
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
    <%= render partial: 'spree/shared/google_analytics.js' %>
    <%= render partial: 'spree/shared/header' %>
        <%= breadcrumbs(@taxon) %>

        <%= render partial: 'spree/shared/sidebar' if content_for? :sidebar %>
          <%= flash_messages %>
          <%= yield %>

        <%= yield :templates %>
        <%= render partial: 'spree/shared/footer' %>
  </body>
</html>

app/views/spree/orders/_form.html.slim
  = render partial: 'spree/shared/error_messages', locals: { target: @order }
  .table-responsive.cart_info data-hook=""
    table.table.table-condensed 
      thead
        tr.cart_menu data-hook="cart_items_headers" 
          th.image colspan="2" = Spree.t(:item)
          th.price= Spree.t(:price)
          th.quantity= Spree.t(:qty)
          th.total= Spree.t(:total)
          th.cart-item-delete-header
      tbody#line_items data-hook="" 
        = render partial: 'spree/orders/line_item', collection: order_form.object.line_items, locals: { order_form: order_form }
      - if @order.adjustments.nonzero.exists? || @order.line_item_adjustments.nonzero.exists? || @order.shipment_adjustments.nonzero.exists? || @order.shipments.any?
        tr.cart-subtotal
          td align="right" colspan="4" 
            h5= Spree.t(:cart_subtotal, count: @order.line_items.sum(:quantity))
          td colspan="" 
            h5= order_form.object.display_item_total
          td
        = render "spree/orders/adjustments"
      tr.warning.cart-total
        td align="right" colspan="4" 
          h5= Spree.t(:total)
        td.lead colspan="" = order_form.object.display_total
        td

app/views/spree/orders/edit.html.slim
section#cart_items
  .container    
    - @body_id = 'cart'
    div data-hook="cart_container" 
      / h1= Spree.t(:shopping_cart)
      - if @order.line_items.empty?
        div data-hook="empty_cart" 
          .alert.alert-info= Spree.t(:your_cart_is_empty)
          p= link_to Spree.t(:continue_shopping), products_path, class: 'btn btn-default'
      - else
        div data-hook="outside_cart_form" 
          = form_for @order, url: update_cart_path, html: { id: 'update-cart' } do |order_form|
            div data-hook="inside_cart_form" 
              .table-responsive data-hook="cart_items" 
                = render partial: 'form', locals: { order_form: order_form }
              .links.col-md-3.navbar-form.pull-right.text-right data-hook="cart_buttons" 
                .form-group
                  = button_tag class: 'btn btn-theme', id: 'update-button' do
                    = Spree.t(:update)
                  = button_tag class: 'btn btn-success', id: 'checkout-link', name: 'checkout' do
                    = Spree.t(:checkout)
              .col-md-6.form-inline.pull-right data-hook="coupon_code" 
                label
                  = order_form.label :coupon_code
                  = order_form.text_field :coupon_code, size: '30', class: 'form-control'
                  = button_tag Spree.t(:coupon_code_apply), class: 'btn btn-default'
        #empty-cart.col-md-3.pull-left data-hook="" 
          = form_tag empty_cart_path, method: :put do
            p#clear_cart_link data-hook="" 
              = submit_tag Spree.t(:empty_cart), class: 'btn btn-default'
              = Spree.t(:or)
              = link_to Spree.t(:continue_shopping), products_path, class: 'continue'
javascript:
  | Spree.current_order_id = "#{@order.number}"
  | Spree.current_order_token = "#{@order.guest_token}"

app/views/spree/products/_cart_form.html.slim
= form_for :order, url: populate_orders_path do |f|
  #inside-product-cart-form.row data-hook="inside_product_cart_form" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer" 
    - if @product.variants_and_option_values(current_currency).any?
      #product-variants.col-md-6
        h3.product-section-title= Spree.t(:variants)
        ul.list-group
          - @product.variants_and_option_values(current_currency).each_with_index do |variant, index|
            li
              = radio_button_tag "variant_id", variant.id, index == 0,   
                'data-price' => variant.price_in(current_currency).money,
                'data-in-stock' => variant.can_supply?                   
              = label_tag "variant_id_#{ variant.id }" do
                span.variant-description
                  = variant_options variant
                - if variant_price variant
                  span.price.diff= variant_price variant
                - unless variant.can_supply?
                  span.out-of-stock= Spree.t(:out_of_stock)
    - else
      = hidden_field_tag "variant_id", @product.master.id
    - if @product.price_in(current_currency) && !@product.price.nil?
      .col-md-12
        span
          span = display_price(@product)
          - if @product.can_supply?
            = number_field_tag :quantity, 1, class: 'title form-control', min: 1
            = button_tag class: 'btn btn-fefault cart', id: 'add-to-cart-button', type: :submit do
              = Spree.t(:add_to_cart)

      .col-md-12 data-hook="product_price" 
        #product-price
          / h6.product-section-title= Spree.t(:price)
          / div
          /   span.lead.price.selling itemprop="price" 
          /     = display_price(@product)
            span content="#{@product.currency}" itemprop="priceCurrency" 
          - if @product.master.can_supply?
            link href="https://schema.org/InStock" itemprop="availability" /
          - elsif @product.variants.empty?
            br/
            span.out-of-stock= Spree.t(:out_of_stock)
        / - if @product.can_supply?
        /   .add-to-cart
        /     br/
        /     .input-group
        /       = number_field_tag :quantity, 1, class: 'title form-control', min: 1
        /       span.input-group-btn
        /         = button_tag class: 'btn btn-fefault cart', id: 'add-to-cart-button', type: :submit do
        /           = Spree.t(:add_to_cart)
    - else
      #product-price
        br/
        div
          span.price.selling itemprop="price" 
            = Spree.t('product_not_available_in_this_currency')

app/views/spree/products/index.html.slim
.container
  - if params[:keywords]
    div data-hook="search_results" 
      - if @products.empty?
        h6.search-results-title= Spree.t(:no_products_found)
      - else
        = render partial: 'spree/shared/products', locals: { products: @products, taxon: @taxon }
  - else
    div data-hook="homepage_products" 
      - cache(cache_key_for_products) do
        = render partial: 'spree/shared/products', locals: { products: @products, taxon: @taxon }

app/views/spree/profiles/_form.html.slim
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      h2 = "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      ul
        - @profile.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :referral_id
    = f.text_field :referral_id
  .field
    = f.label :user_id
    = f.text_field :user_id
  .actions = f.submit

app/views/spree/profiles/edit.html.slim
h1 Editing profile

== render 'form'

= link_to 'Show', @profile
'  |
= link_to 'Back', profiles_path

app/views/spree/profiles/index.html.slim
.container
  -if @profiles.present?
    .row
      - @profiles.each do |profile|
        .col-md-4
          .profile-card
            h3 =profile.full_name
            .uuid =profile.uuid
            .secondary-options
               = link_to 'Show', profile
               = link_to 'Edit', edit_profile_path(profile)
               = link_to 'Destroy', profile, data: { confirm: 'Are you sure?' }, method: :delete
    .row  
      -unless @profiles.collect(&:children).flatten.blank?
        h3 Your referred Users
        - @profiles.collect(&:children).flatten.each do |child|
          .col-md-4
            .profile-card
              h3 =child.full_name
              .uuid =child.uuid
              .secondary-options
                 = link_to 'Show', child
                 = link_to 'Edit', edit_profile_path(child)
                 = link_to 'Destroy', child, data: { confirm: 'Are you sure?' }, method: :delete
      br
    -if @profiles.count < 5
      .col-md-4
        .profile-card
          = link_to 'New Profile', new_profile_path
  
            

app/views/spree/profiles/new.html.slim
.row
	.col-md-6.col-md-offset-3
		.profile
			.new-profile
				h1 New profile

				== render 'form'

				= link_to 'Back', profiles_path

app/views/spree/profiles/show.html.slim
.container
	.row
		.col-md-6.col-md-offset-3
			.profile-show-page	
				p#notice = notice

				p
				  strong First name:
				  = @profile.first_name
				p
				  strong Last name:
				  = @profile.last_name
				p
				  strong Uuid:
				  = @profile.uuid
				p
				  strong User:
				  = @profile.user_id

				= link_to 'Edit', edit_profile_path(@profile)
				'  |
				= link_to 'Back', profiles_path
				' | 
				= link_to 'Add New Profile', new_profile_path

app/views/spree/shared/_footer.html.slim
section#footer
	.companyinfo
		p Copyright @ 2017 sphUrta.com

app/views/spree/shared/_products.html.slim
/ -products.each do |product|
/   .col-sm-3
/     .product-image-wrapper
/       .single-products
        .productinfo.text-center
          img alt="" src="images/home/product1.jpg" /
          h2 $56
          p Easy Polo Black Edition
          a.btn.btn-default.add-to-cart href="#" 
            i.fa.fa-shopping-cart
            | Add to cart
        .product-overlay
          .overlay-content
            h2 $56
            p Easy Polo Black Edition
            a.btn.btn-default.add-to-cart href="#" 
              i.fa.fa-shopping-cart
              | Add to cart
/       .choose
/         ul.nav.nav-pills.nav-justified
/           li
/             a href="#" 
/               i.fa.fa-plus-square
/               | Add to wishlist
/           li
/             a href="#" 
/               i.fa.fa-plus-square
/               | Add to compare
- if products.any?
  #products.row data-hook="" 
    - products.each do |product|
      - url = spree.product_path(product, taxon_id: @taxon.try(:id))
      .col-md-3.col-sm-6.col-xs-6.product-list-item data-hook="products_list_item" id="product_#{product.id}" itemscope="" itemtype="https://schema.org/Product" 
        .product-image-wrapper
          .single-products
            .productinfo.text-center
              = small_image(product, itemprop: "image")
              h2 = display_price(product)
              p =product.name
              a.btn.btn-default.add-to-cart href=product_path(product)  
                i.fa.fa-shopping-cart
                | Add to cart
            .product-overlay
              .overlay-content
                h2 = display_price(product)
                p =product.name
                a.btn.btn-default.add-to-cart href=product_path(product) 
                  i.fa.fa-shopping-cart
                  | Add to cart
            / - cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : cache_key_for_product(product)) do
            /   .panel-body.text-center.product-body
            /     = link_to url, itemprop: "url" do
            /       = small_image(product, itemprop: "image")
    
            /       = content_tag(:span, truncate(product.name, length: 50), class: 'info', itemprop: "name", title: product.name)
            /     br/
              .panel-footer.text-center
                span itemprop="offers" itemscope="" itemtype="https://schema.org/Offer" 
                  span.price.selling.lead itemprop="price" = display_price(product)
    - reset_cycle("classes")

app/views/spree/user_registrations/new.html.slim
section#singup.window-height
  .container
    .row
      .col-sm-6.col-sm-offset-3
        .form-style
          = form_for @user  , html: {class: "custom-form reg-form"}, :as => :spree_user, url: spree.registration_path do |f|
            .row
              .form-group.col-xs-12
                h4.title Your Personal Details    
              .form-group.col-xs-12
                = f.email_field :email, :class => 'form-control reg-email',maxlength: "100", :tabindex => 1, :placeholder => 'E-Mail*'
                span#invalid-email
              .form-group.col-sm-6.col-xs-12
                = f.password_field :password, :class => 'form-control reg-password', maxlength: "30",:tabindex => 2, :placeholder => 'Password*'
                span#password-error
              .form-group.col-sm-6.col-xs-12
                = f.password_field :password_confirmation, :class => 'form-control reg-password-confirm',maxlength: "30", :tabindex => 2, :placeholder => 'Confirm Password*'
                span#password-confirm-error
              .form-group.col-sm-6.col-xs-12
                = f.text_field :referral_id, :class => 'form-control reg-password',:tabindex => 2, :placeholder => 'Referral Id'
              .form-group.col-xs-12.text-center
                = f.submit 'Sign Up', :tabindex => 3, id: "continue-btn"

app/views/spree/user_sessions/new.html.slim
section#singup.window-height
  .container
    .row
      .col-sm-6.col-sm-offset-3
        
        .form-style
          h4.login-title
            |Log in as existing customer  
          = form_for Spree::User.new, html: {class: "custom-form"}, :as => :spree_user, :url => spree.create_new_session_path do |f|
            .form-group
              label.form-label for="email" 
                |Email
                span.required *
              = f.email_field :email, class: "form-control", id: "email"
            .form-group
              label.form-label for="pwd" 
                |Password
                span.required *
              = f.password_field :password, class: "form-control", id: "pwd"
            .forgot-password-wrap
              a.forgot-link href=spree.recover_password_path forgot username or password?
            .form-footer
              = f.submit "Log In", class: "form-btn"
          hr
           a.forgot-link href=signup_path or create a new account


- content_for :title do 
  | Login | Felix Gray